### PR TITLE
Add more token-2022 Examples

### PR DESCRIPTION
**Pull request by shivamSspirit**
use token-2022 feature with Transfer Fees type extension

### CODE REVIEW

**Comment by buffalojoec** [comment]
Ahh dang bro! @valentinmadrid just merged in some transfer fee token examples.

Any chance you can run a diff on your implementation vs. his? We can go with whichever one is more descriptive

**Comment by valentinmadrid** [comment]
You could add the withdraw_withheld_tokens_from_accounts instruction to the example.

**Comment by shivamSspirit** [comment]
> Ahh dang bro! @valentinmadrid just merged in some transfer fee token examples.
> 
> Any chance you can run a diff on your implementation vs. his? We can go with whichever one is more descriptive

I think you merged the valentinmadrid example no issues now I work on a different example

**Comment by shivamSspirit** [comment]
> You could add the withdraw_withheld_tokens_from_accounts instruction to the example.

yes i will work on this withdraw_withheld_tokens_from_accounts

**Comment by buffalojoec** [comment]
Please remove the transfer fee example from your PR and rename the folder for "Reallocating Space" to contain the proper spelling of "reallocate"

**Comment by buffalojoec** [comment]
Looks like you've still got the old "relocate" directory in there, and I also noticed you mis-spelled "account" in one of the other directories. Plus, I still see transfer fee.

**Comment by shivamSspirit** [comment]
I will look into this

**Comment by shivamSspirit** [comment]
I think I removed those examples that are preexisted

see here: https://github.com/shivamsoni00/web3-examples/tree/newtoken2022/tokens/token-2022

**Review by buffalojoec — APPROVED** [review]

**Pull request merged**
